### ISSUE TITLE
Differentiate secret vs. non-secret fields in binding credentials

### ISSUE THREAD

**Issue by bmelville** [openservicebrokerapi/servicebroker#117]
We have come across this use-case several times in various places. Given the output of a Bind() operation, we would like to be able to understand which fields within the credential are secret and must be treated so, and which are non-secret and may be treated less securely.

For example, if the output of a binding is:

```
credential:
  username: admin
  password: mypassword
  hostname: localhost
  port: 8080
```

`username` and `password` may be treated as a secret in UI or in credential handling by the controller, while `hostname` and `port` may be treated as general configuration data.

Proposal is introduced as part of the proposal for #116: https://docs.google.com/document/d/1JbsJgqgNtqthcfYwK_KbS6C8sjElrZNgoLhu40dUPAs/edit?usp=sharing

**Comment by avade** [comment]
We are looking at how to secure the `credential` object as well. I hadn't thought of the UI implications.

I think our plan is to share the design with the CF community before the holidays. I will make sure to post it here as well.

Is this issue more of a use case for #116?  Do you see another section in the binding response? As a rough example:

```
credential:
  username: admin
  password: mypassword
configuration:
  hostname: localhost
  port: 8080
```

**Comment by bmelville** [comment]
I was thinking of it as a feature of #116. I think we will also want to be able to hint at secret input parameters as well (e.g., what if an input to binding is `password` and the UI should know it needs to "dot" it out when I'm typing it), so this could easily be an extension to all of our schema support.

e.g.,

```
plans:
  schemas:
    service_bindings:
      create:
        credential:
          properties:
            password:
              type: string
              x-servicebroker-secret: true
            hostname:
              type: string
```

Does this seem like a sane approach? I could also see benefits to separating as fields in the API, where each field has more explicit security semantics, e.g., one is encrypted or secured somehow, the other not.
